name: 'Pull request reviews reminder action'
description: 'Automatically send notification for pull requests waiting for reviewers'
branding:
  icon: 'bell'
  color: 'red'
inputs:
  slackBotToken:
    description: 'slackBotToken'
    required: true
  slackBotChannelID:
    description: 'slackBotChannelID'
    required: true
  github-provider-map:
    description: 'Map GitHub username to Slack user IDs. Eg: "DavideViolante:UABCDEFGH,foobar123:UIHJKLMNO"'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
